export type Activity = {
  id: string;
  name: string;
  nameAr: string;
  icon: string;
  category: string;
  niyyahText: string;
  niyyahTextAr: string;
  hadithRef?: string;
  defaultTime?: string;
  color: string;
};

export type NiyyahOption = {
  id: string;
  activityId: string;
  level: "basic" | "advanced";
  text: string;
  textAr: string;
  source?: string;
  profileTag?: "homemaker" | "student" | "professional" | "parent";
};

export type EducationEntry = {
  id: string;
  title: string;
  titleAr: string;
  category: string;
  content: string;
  contentAr: string;
  source: string;
  keywords: string[];
};

export const DEFAULT_ACTIVITIES: Activity[] = [
  {
    id: "fajr",
    name: "Fajr Prayer",
    nameAr: "صلاة الفجر",
    icon: "sunrise",
    category: "worship",
    niyyahText: "I intend to pray Fajr seeking the pleasure of Allah and to start my day in His remembrance.",
    niyyahTextAr: "نويت أن أصلي الفجر ابتغاء وجه الله وذكره في بداية يومي.",
    hadithRef: "Bukhari 6407",
    defaultTime: "05:00",
    color: "#F59E0B",
  },
  {
    id: "breakfast",
    name: "Eating & Drinking",
    nameAr: "الأكل والشرب",
    icon: "coffee",
    category: "daily",
    niyyahText: "I intend this meal to nourish my body as a trust from Allah, gaining strength for worship and service.",
    niyyahTextAr: "نويت هذه الوجبة لتغذية جسمي أمانة من الله، لأكتسب القوة للعبادة والخدمة.",
    hadithRef: "Muslim 2013",
    defaultTime: "07:00",
    color: "#10B981",
  },
  {
    id: "work",
    name: "Work / Earning",
    nameAr: "العمل / الكسب",
    icon: "briefcase",
    category: "productivity",
    niyyahText: "I intend my work seeking halal provision for my family and to benefit society, as an act of worship.",
    niyyahTextAr: "نويت عملي طلباً للرزق الحلال لعائلتي وخدمة المجتمع، عبادةً لله.",
    hadithRef: "Tabarani",
    defaultTime: "09:00",
    color: "#3B82F6",
  },
  {
    id: "exercise",
    name: "Exercise",
    nameAr: "الرياضة",
    icon: "activity",
    category: "health",
    niyyahText: "I intend this exercise to maintain the health and strength of this body, a trust from Allah.",
    niyyahTextAr: "نويت هذه الرياضة للحفاظ على صحة هذا الجسم وقوته، أمانة من الله.",
    hadithRef: "Muslim 2664",
    defaultTime: "07:30",
    color: "#EF4444",
  },
  {
    id: "cooking",
    name: "Cooking / Meal Prep",
    nameAr: "الطبخ / تحضير الطعام",
    icon: "zap",
    category: "daily",
    niyyahText: "I intend this cooking to prepare nourishing food for my household as a service to Allah.",
    niyyahTextAr: "نويت هذا الطبخ لتحضير طعام مغذٍ لعائلتي خدمةً لله.",
    hadithRef: "Tirmidhi 1897",
    color: "#F97316",
  },
  {
    id: "cleaning",
    name: "Cleaning / Chores",
    nameAr: "التنظيف / الأعمال المنزلية",
    icon: "wind",
    category: "daily",
    niyyahText: "I intend this cleaning to maintain a pure, blessed home following the Sunnah of cleanliness.",
    niyyahTextAr: "نويت هذا التنظيف للحفاظ على بيت طاهر ومبارك اتباعاً لسنة النظافة.",
    hadithRef: "Muslim 223",
    color: "#06B6D4",
  },
  {
    id: "lunch",
    name: "Lunch",
    nameAr: "الغداء",
    icon: "sun",
    category: "daily",
    niyyahText: "I intend this meal with gratitude, to sustain my body for continued service to Allah and His creation.",
    niyyahTextAr: "نويت هذه الوجبة بامتنان، لاستدامة جسمي في خدمة الله وخلقه.",
    defaultTime: "13:00",
    color: "#F97316",
  },
  {
    id: "dhuhur",
    name: "Dhuhr Prayer",
    nameAr: "صلاة الظهر",
    icon: "sun",
    category: "worship",
    niyyahText: "I intend to pray Dhuhr, pausing from worldly affairs to remember Allah in the middle of my day.",
    niyyahTextAr: "نويت أن أصلي الظهر، متوقفاً عن شؤون الدنيا لذكر الله في منتصف يومي.",
    defaultTime: "13:30",
    color: "#FBBF24",
  },
  {
    id: "commute",
    name: "Commute",
    nameAr: "التنقل",
    icon: "map-pin",
    category: "daily",
    niyyahText: "I intend this journey for Allah's sake, seeking to fulfill my duties and trusting in His protection.",
    niyyahTextAr: "نويت هذا السفر لله، ساعياً لأداء واجباتي وثقتي بحمايته.",
    defaultTime: "08:00",
    color: "#8B5CF6",
  },
  {
    id: "asr",
    name: "Asr Prayer",
    nameAr: "صلاة العصر",
    icon: "clock",
    category: "worship",
    niyyahText: "I intend to pray Asr, the middle prayer that the Prophet ﷺ especially emphasized.",
    niyyahTextAr: "نويت أن أصلي العصر، الصلاة الوسطى التي أكد عليها النبي ﷺ.",
    hadithRef: "Bukhari 552",
    defaultTime: "16:00",
    color: "#F59E0B",
  },
  {
    id: "family",
    name: "Family Time",
    nameAr: "وقت العائلة",
    icon: "heart",
    category: "relationships",
    niyyahText: "I intend this time with family to fulfill their rights, strengthen ties, and embody the Sunnah of care.",
    niyyahTextAr: "نويت هذا الوقت مع العائلة لأداء حقوقهم، وتقوية الروابط، وتجسيد سنة الرعاية.",
    hadithRef: "Tirmidhi 1897",
    defaultTime: "18:00",
    color: "#EC4899",
  },
  {
    id: "maghrib",
    name: "Maghrib Prayer",
    nameAr: "صلاة المغرب",
    icon: "sunset",
    category: "worship",
    niyyahText: "I intend to pray Maghrib with gratitude for the day's blessings, as the sun sets.",
    niyyahTextAr: "نويت أن أصلي المغرب بامتنان على نعم اليوم، عند غروب الشمس.",
    defaultTime: "18:30",
    color: "#F97316",
  },
  {
    id: "dinner",
    name: "Dinner",
    nameAr: "العشاء",
    icon: "moon",
    category: "daily",
    niyyahText: "I intend this evening meal with Bismillah, sharing sustenance and gathering with loved ones for Allah.",
    niyyahTextAr: "نويت وجبة المساء بسم الله، مشاركاً الرزق والتجمع مع الأحبة لله.",
    defaultTime: "20:00",
    color: "#6366F1",
  },
  {
    id: "isha",
    name: "Isha Prayer",
    nameAr: "صلاة العشاء",
    icon: "moon",
    category: "worship",
    niyyahText: "I intend to pray Isha, ending my day in submission to Allah before sleep.",
    niyyahTextAr: "نويت أن أصلي العشاء، منهياً يومي بالخضوع لله قبل النوم.",
    hadithRef: "Muslim 657",
    defaultTime: "21:00",
    color: "#1E40AF",
  },
  {
    id: "sleep",
    name: "Sleep",
    nameAr: "النوم",
    icon: "moon",
    category: "daily",
    niyyahText: "I intend this sleep to rest my body, a gift from Allah, so I may wake with renewed energy for worship.",
    niyyahTextAr: "نويت هذا النوم لراحة جسمي، هبة من الله، لأستيقظ بطاقة متجددة للعبادة.",
    hadithRef: "Bukhari 247",
    defaultTime: "22:30",
    color: "#7C3AED",
  },
  {
    id: "reading",
    name: "Reading / Learning",
    nameAr: "القراءة / التعلم",
    icon: "book-open",
    category: "productivity",
    niyyahText: "I intend this learning to seek knowledge, as seeking knowledge is an obligation in Islam.",
    niyyahTextAr: "نويت هذا التعلم لطلب العلم، فطلب العلم فريضة في الإسلام.",
    hadithRef: "Ibn Majah 224",
    defaultTime: "20:00",
    color: "#059669",
  },
  {
    id: "charity",
    name: "Giving / Charity",
    nameAr: "الصدقة",
    icon: "gift",
    category: "worship",
    niyyahText: "I intend this giving sincerely for Allah's sake alone, seeking neither praise nor worldly return.",
    niyyahTextAr: "نويت هذا العطاء خالصاً لوجه الله، لا أبتغي مدحاً ولا عوضاً دنيوياً.",
    hadithRef: "Bukhari 1419",
    color: "#D97706",
  },
];

// ─── Multi-Niyyah Options ────────────────────────────────────────────────────

export const NIYYAH_OPTIONS: NiyyahOption[] = [
  // ── Eating & Drinking ──
  {
    id: "eat_basic",
    activityId: "breakfast",
    level: "basic",
    text: "Gain strength for ibadah",
    textAr: "اكتساب القوة للعبادة",
    source: "Muslim 2013",
  },
  {
    id: "eat_1",
    activityId: "breakfast",
    level: "advanced",
    text: "Follow Sunnah manners (Bismillah, right hand, sitting)",
    textAr: "اتباع آداب السنة (بسم الله، باليد اليمنى، جلوساً)",
    source: "Bukhari 5376",
  },
  {
    id: "eat_2",
    activityId: "breakfast",
    level: "advanced",
    text: "Recharge body for the next prayer",
    textAr: "تجديد طاقة الجسم للصلاة القادمة",
  },
  {
    id: "eat_3",
    activityId: "breakfast",
    level: "advanced",
    text: "Express gratitude to Allah for His rizq",
    textAr: "التعبير عن الشكر لله على رزقه",
    source: "Quran 14:7",
  },
  {
    id: "eat_4",
    activityId: "breakfast",
    level: "advanced",
    text: "Eat moderately to avoid heedlessness",
    textAr: "الأكل باعتدال لتجنب الغفلة",
    source: "Ibn Majah 3349",
  },
  // also link to lunch/dinner
  {
    id: "lunch_basic",
    activityId: "lunch",
    level: "basic",
    text: "Sustain the body as Allah's trust",
    textAr: "إدامة الجسم أمانةً من الله",
  },
  {
    id: "lunch_1",
    activityId: "lunch",
    level: "advanced",
    text: "Follow Sunnah manners (Bismillah, right hand)",
    textAr: "اتباع آداب السنة (بسم الله، اليد اليمنى)",
    source: "Bukhari 5376",
  },
  {
    id: "lunch_2",
    activityId: "lunch",
    level: "advanced",
    text: "Recharge for Asr prayer and afternoon duties",
    textAr: "تجديد الطاقة لصلاة العصر وواجبات بعد الظهر",
  },
  {
    id: "lunch_3",
    activityId: "lunch",
    level: "advanced",
    text: "Thank Allah for continued provision and health",
    textAr: "شكر الله على استمرار الرزق والصحة",
  },
  {
    id: "dinner_basic",
    activityId: "dinner",
    level: "basic",
    text: "Gather with family in Allah's name",
    textAr: "التجمع مع العائلة باسم الله",
  },
  {
    id: "dinner_1",
    activityId: "dinner",
    level: "advanced",
    text: "Follow Sunnah manners (Bismillah, right hand)",
    textAr: "اتباع آداب السنة (بسم الله، اليد اليمنى)",
    source: "Bukhari 5376",
  },
  {
    id: "dinner_2",
    activityId: "dinner",
    level: "advanced",
    text: "Strengthen family bonds as an act of worship",
    textAr: "تعزيز روابط الأسرة كعبادة",
    source: "Tirmidhi 1897",
  },
  {
    id: "dinner_3",
    activityId: "dinner",
    level: "advanced",
    text: "End the day with gratitude before Isha",
    textAr: "ختام اليوم بالشكر قبل صلاة العشاء",
  },

  // ── Work / Earning ──
  {
    id: "work_basic",
    activityId: "work",
    level: "basic",
    text: "Earn halal provision for myself and family",
    textAr: "كسب الرزق الحلال لنفسي وعائلتي",
    source: "Tabarani",
  },
  {
    id: "work_1",
    activityId: "work",
    level: "advanced",
    text: "Providing for family as a form of sadaqah",
    textAr: "الإنفاق على الأسرة كصدقة",
    source: "Muslim 994",
  },
  {
    id: "work_2",
    activityId: "work",
    level: "advanced",
    text: "Avoid dependence on others and preserve dignity",
    textAr: "تجنب التعلق بالآخرين والحفاظ على الكرامة",
    source: "Bukhari 1470",
  },
  {
    id: "work_3",
    activityId: "work",
    level: "advanced",
    text: "Use future earnings for zakat and good causes",
    textAr: "استخدام الأرباح المستقبلية للزكاة والأعمال الخيرية",
    source: "Quran 2:177",
  },
  {
    id: "work_4",
    activityId: "work",
    level: "advanced",
    text: "Benefit society and leave a positive legacy",
    textAr: "إفادة المجتمع وترك إرث إيجابي",
  },
  {
    id: "work_professional_1",
    activityId: "work",
    level: "advanced",
    text: "Work with honesty and excellence as an act of worship",
    textAr: "العمل بأمانة وإتقان كعبادة",
    source: "Tabarani",
    profileTag: "professional",
  },
  {
    id: "work_professional_2",
    activityId: "work",
    level: "advanced",
    text: "Use earnings in Allah's path through zakat and sadaqah",
    textAr: "إنفاق الكسب في سبيل الله بالزكاة والصدقة",
    source: "Quran 2:261",
    profileTag: "professional",
  },
  {
    id: "work_professional_3",
    activityId: "work",
    level: "advanced",
    text: "Earn halal provision as sadaqah for the family",
    textAr: "كسب الرزق الحلال كصدقة على العائلة",
    source: "Muslim 994",
    profileTag: "professional",
  },

  // ── Exercise ──
  {
    id: "exercise_basic",
    activityId: "exercise",
    level: "basic",
    text: "Care for the body as Allah's amanah",
    textAr: "الاعتناء بالجسم أمانةً من الله",
    source: "Muslim 2664",
  },
  {
    id: "exercise_1",
    activityId: "exercise",
    level: "advanced",
    text: "Build strength for longer salah and fasting",
    textAr: "بناء القوة لصلاة أطول وصيام أفضل",
  },
  {
    id: "exercise_2",
    activityId: "exercise",
    level: "advanced",
    text: "Better serve family and community with strong health",
    textAr: "خدمة العائلة والمجتمع بصحة أفضل",
    source: "Tirmidhi 1897",
  },
  {
    id: "exercise_3",
    activityId: "exercise",
    level: "advanced",
    text: "Follow the Sunnah of the strong believer",
    textAr: "اتباع سنة المؤمن القوي",
    source: "Muslim 2664",
  },
  {
    id: "exercise_4",
    activityId: "exercise",
    level: "advanced",
    text: "Maintain energy for night prayers (Tahajjud)",
    textAr: "الحفاظ على الطاقة لصلاة الليل (التهجد)",
  },

  // ── Cooking ──
  {
    id: "cooking_basic",
    activityId: "cooking",
    level: "basic",
    text: "Prepare nourishing food for the household",
    textAr: "تحضير طعام مغذٍ للأسرة",
  },
  {
    id: "cooking_1",
    activityId: "cooking",
    level: "advanced",
    text: "Feed family as an act of charity and love",
    textAr: "إطعام العائلة كصدقة ومحبة",
    source: "Muslim 994",
  },
  {
    id: "cooking_2",
    activityId: "cooking",
    level: "advanced",
    text: "Serve spouse and household — a marital Sunnah",
    textAr: "خدمة الزوج والأسرة — سنة زوجية",
    source: "Tirmidhi 1162",
    profileTag: "homemaker",
  },
  {
    id: "cooking_3",
    activityId: "cooking",
    level: "advanced",
    text: "Maintain household health for worship",
    textAr: "صون صحة الأسرة للعبادة",
  },
  {
    id: "cooking_4",
    activityId: "cooking",
    level: "advanced",
    text: "Practice mindful Bismillah at every step",
    textAr: "ممارسة بسم الله بوعي في كل خطوة",
    source: "Bukhari 5376",
  },
  {
    id: "cooking_homemaker_1",
    activityId: "cooking",
    level: "advanced",
    text: "Make the home a place of blessing and warmth",
    textAr: "جعل البيت مكانًا من البركة والدفء",
    profileTag: "homemaker",
  },
  {
    id: "cooking_homemaker_2",
    activityId: "cooking",
    level: "advanced",
    text: "Obey household duties as a form of worship",
    textAr: "أداء الواجبات المنزلية كعبادة",
    profileTag: "homemaker",
  },
  {
    id: "cooking_parent_1",
    activityId: "cooking",
    level: "advanced",
    text: "Raise righteous children through nourishing food",
    textAr: "تربية أطفال صالحين من خلال الطعام المغذي",
    profileTag: "parent",
  },

  // ── Cleaning / Chores ──
  {
    id: "cleaning_basic",
    activityId: "cleaning",
    level: "basic",
    text: "Maintain a clean home following Sunnah of cleanliness",
    textAr: "الحفاظ على نظافة البيت اتباعاً لسنة النظافة",
    source: "Muslim 223",
  },
  {
    id: "cleaning_1",
    activityId: "cleaning",
    level: "advanced",
    text: "Create a peaceful space conducive to worship",
    textAr: "خلق مساحة هادئة مواتية للعبادة",
  },
  {
    id: "cleaning_2",
    activityId: "cleaning",
    level: "advanced",
    text: "Serve family with kindness and sincerity",
    textAr: "خدمة العائلة بطيب نفس وإخلاص",
    profileTag: "homemaker",
  },
  {
    id: "cleaning_3",
    activityId: "cleaning",
    level: "advanced",
    text: "Embody that 'cleanliness is half of faith'",
    textAr: "تجسيد أن النظافة نصف الإيمان",
    source: "Muslim 223",
  },
  {
    id: "cleaning_4",
    activityId: "cleaning",
    level: "advanced",
    text: "Teach children the value of order and cleanliness",
    textAr: "تعليم الأطفال قيمة النظام والنظافة",
    profileTag: "parent",
  },
  {
    id: "cleaning_homemaker_1",
    activityId: "cleaning",
    level: "advanced",
    text: "Maintain the home as a blessed place of worship",
    textAr: "صون البيت كمكان مبارك للعبادة",
    profileTag: "homemaker",
  },
  {
    id: "cleaning_parent_1",
    activityId: "cleaning",
    level: "advanced",
    text: "Raise children who appreciate order and purity",
    textAr: "تربية أطفال يقدّرون النظام والطهارة",
    profileTag: "parent",
  },

  // ── Sleeping ──
  {
    id: "sleep_basic",
    activityId: "sleep",
    level: "basic",
    text: "Rest the body to recharge for worship",
    textAr: "إراحة الجسم لتجديد طاقته للعبادة",
    source: "Bukhari 247",
  },
  {
    id: "sleep_1",
    activityId: "sleep",
    level: "advanced",
    text: "Wake for Tahajjud — set the intention now",
    textAr: "الاستيقاظ للتهجد — اعقد النية الآن",
    source: "Bukhari 1145",
  },
  {
    id: "sleep_2",
    activityId: "sleep",
    level: "advanced",
    text: "Preserve health as a trust from Allah",
    textAr: "صون الصحة أمانةً من الله",
  },
  {
    id: "sleep_3",
    activityId: "sleep",
    level: "advanced",
    text: "Follow Sunnah sleep du'a and right-side posture",
    textAr: "اتباع دعاء النوم السني والنوم على الجانب الأيمن",
    source: "Bukhari 247",
  },
  {
    id: "sleep_4",
    activityId: "sleep",
    level: "advanced",
    text: "Rest as counted reward — like a night of worship",
    textAr: "الراحة كأجر محتسب — كليلة من العبادة",
    source: "Abu Dawud 5056",
  },

  // ── Prayers (shared pattern) ──
  {
    id: "fajr_basic",
    activityId: "fajr",
    level: "basic",
    text: "Obey Allah's command for Fajr prayer",
    textAr: "طاعة أمر الله في صلاة الفجر",
    source: "Quran 17:78",
  },
  {
    id: "fajr_1",
    activityId: "fajr",
    level: "advanced",
    text: "Start the day under Allah's protection",
    textAr: "بدء اليوم تحت حماية الله",
    source: "Abu Dawud 5082",
  },
  {
    id: "fajr_2",
    activityId: "fajr",
    level: "advanced",
    text: "Witness the dawn — a moment witnessed by angels",
    textAr: "شهود الفجر — لحظة يشهدها الملائكة",
    source: "Quran 17:78",
  },
  {
    id: "fajr_3",
    activityId: "fajr",
    level: "advanced",
    text: "Earn the reward greater than the world and all it contains",
    textAr: "كسب الأجر الأعظم من الدنيا وما فيها",
    source: "Muslim 725",
  },
  {
    id: "dhuhur_basic",
    activityId: "dhuhur",
    level: "basic",
    text: "Pause from work to remember Allah",
    textAr: "التوقف عن العمل لذكر الله",
  },
  {
    id: "dhuhur_1",
    activityId: "dhuhur",
    level: "advanced",
    text: "Seek forgiveness for the morning's shortcomings",
    textAr: "طلب المغفرة عن قصور الصباح",
  },
  {
    id: "dhuhur_2",
    activityId: "dhuhur",
    level: "advanced",
    text: "Renew gratitude for a productive morning",
    textAr: "تجديد الشكر على صباح مثمر",
  },
  {
    id: "asr_basic",
    activityId: "asr",
    level: "basic",
    text: "Guard the middle prayer as commanded",
    textAr: "حفظ الصلاة الوسطى كما أُمرنا",
    source: "Quran 2:238",
  },
  {
    id: "asr_1",
    activityId: "asr",
    level: "advanced",
    text: "Close the work-day chapter with Allah's remembrance",
    textAr: "إغلاق فصل يوم العمل بذكر الله",
  },
  {
    id: "asr_2",
    activityId: "asr",
    level: "advanced",
    text: "Protect from the warning for missing Asr",
    textAr: "الحماية من التحذير لمن يفوته العصر",
    source: "Bukhari 552",
  },
  {
    id: "maghrib_basic",
    activityId: "maghrib",
    level: "basic",
    text: "Thank Allah for completing another day",
    textAr: "شكر الله على إتمام يوم آخر",
  },
  {
    id: "maghrib_1",
    activityId: "maghrib",
    level: "advanced",
    text: "Seek Maghrib's special time of du'a acceptance",
    textAr: "الحرص على وقت إجابة الدعاء عند المغرب",
  },
  {
    id: "maghrib_2",
    activityId: "maghrib",
    level: "advanced",
    text: "Gather family for prayer and togetherness",
    textAr: "جمع الأسرة للصلاة والتوحد",
  },
  {
    id: "isha_basic",
    activityId: "isha",
    level: "basic",
    text: "End the day in submission to Allah",
    textAr: "ختام اليوم بالخضوع لله",
    source: "Muslim 657",
  },
  {
    id: "isha_1",
    activityId: "isha",
    level: "advanced",
    text: "Guard Isha for its exceptional reward",
    textAr: "الحفاظ على العشاء لأجرها الاستثنائي",
    source: "Muslim 656",
  },
  {
    id: "isha_2",
    activityId: "isha",
    level: "advanced",
    text: "Prepare the heart for peaceful, grateful sleep",
    textAr: "تهيئة القلب للنوم المسالم الشاكر",
  },

  // ── Reading / Learning ──
  {
    id: "reading_basic",
    activityId: "reading",
    level: "basic",
    text: "Seek knowledge as a religious obligation",
    textAr: "طلب العلم واجب ديني",
    source: "Ibn Majah 224",
  },
  {
    id: "reading_1",
    activityId: "reading",
    level: "advanced",
    text: "Improve skills to earn better halal income",
    textAr: "تطوير المهارات لكسب دخل حلال أفضل",
    profileTag: "professional",
  },
  {
    id: "reading_2",
    activityId: "reading",
    level: "advanced",
    text: "Share knowledge as ongoing sadaqah jariyah",
    textAr: "نشر العلم كصدقة جارية",
    source: "Muslim 1631",
  },
  {
    id: "reading_3",
    activityId: "reading",
    level: "advanced",
    text: "Deepen understanding of deen and world",
    textAr: "تعميق فهم الدين والدنيا",
  },
  {
    id: "reading_student_1",
    activityId: "reading",
    level: "advanced",
    text: "Seek knowledge for Allah's sake alone",
    textAr: "طلب العلم لوجه الله وحده",
    source: "Ibn Majah 224",
    profileTag: "student",
  },
  {
    id: "reading_student_2",
    activityId: "reading",
    level: "advanced",
    text: "Apply learning in dawah and service to others",
    textAr: "تطبيق العلم في الدعوة وخدمة الآخرين",
    profileTag: "student",
  },
  {
    id: "reading_student_3",
    activityId: "reading",
    level: "advanced",
    text: "Strengthen the mind for better ibadah",
    textAr: "تقوية العقل لعبادة أفضل",
    profileTag: "student",
  },

  // ── Family Time ──
  {
    id: "family_basic",
    activityId: "family",
    level: "basic",
    text: "Fulfill rights of family as an act of worship",
    textAr: "أداء حقوق العائلة كعبادة",
    source: "Tirmidhi 1897",
  },
  {
    id: "family_1",
    activityId: "family",
    level: "advanced",
    text: "Strengthen blood ties that Allah commanded",
    textAr: "تقوية صلة الرحم التي أوجبها الله",
    source: "Bukhari 5988",
  },
  {
    id: "family_2",
    activityId: "family",
    level: "advanced",
    text: "Model Islamic character for children",
    textAr: "نمذجة الأخلاق الإسلامية للأطفال",
    profileTag: "parent",
  },
  {
    id: "family_3",
    activityId: "family",
    level: "advanced",
    text: "Be among the best to my spouse",
    textAr: "أن أكون من أفضل الناس لزوجي",
    source: "Tirmidhi 3895",
  },
  {
    id: "family_parent_1",
    activityId: "family",
    level: "advanced",
    text: "Raise righteous children who will make du'a for me",
    textAr: "تربية أطفال صالحين يدعون لي",
    source: "Muslim 1631",
    profileTag: "parent",
  },
  {
    id: "family_parent_2",
    activityId: "family",
    level: "advanced",
    text: "Show kindness and patience with children as worship",
    textAr: "معاملة الأطفال بلطف وصبر كعبادة",
    profileTag: "parent",
  },
  {
    id: "family_parent_3",
    activityId: "family",
    level: "advanced",
    text: "Teach the children their deen through daily example",
    textAr: "تعليم الأطفال دينهم من خلال المثال اليومي",
    profileTag: "parent",
  },

  // ── Charity ──
  {
    id: "charity_basic",
    activityId: "charity",
    level: "basic",
    text: "Give purely for Allah's sake alone",
    textAr: "العطاء خالصاً لوجه الله",
    source: "Bukhari 1419",
  },
  {
    id: "charity_1",
    activityId: "charity",
    level: "advanced",
    text: "Purify my wealth through giving",
    textAr: "تطهير مالي من خلال العطاء",
    source: "Quran 9:103",
  },
  {
    id: "charity_2",
    activityId: "charity",
    level: "advanced",
    text: "Seek the sevenfold multiplication Allah promises",
    textAr: "السعي للمضاعفة السبعينية التي وعد الله بها",
    source: "Quran 2:261",
  },
  {
    id: "charity_3",
    activityId: "charity",
    level: "advanced",
    text: "Protect my wealth from loss through sadaqah",
    textAr: "حماية مالي من الضياع بالصدقة",
    source: "Muslim 2588",
  },

  // ── Commute ──
  {
    id: "commute_basic",
    activityId: "commute",
    level: "basic",
    text: "Travel under Allah's protection",
    textAr: "السفر تحت حماية الله",
  },
  {
    id: "commute_1",
    activityId: "commute",
    level: "advanced",
    text: "Fill the journey with dhikr and Quran",
    textAr: "ملء الرحلة بالذكر والقرآن",
    source: "Bukhari 6682",
  },
  {
    id: "commute_2",
    activityId: "commute",
    level: "advanced",
    text: "Recite the travel du'a as prophetic Sunnah",
    textAr: "قراءة دعاء السفر اتباعاً للسنة النبوية",
    source: "Abu Dawud 2602",
  },
  {
    id: "commute_3",
    activityId: "commute",
    level: "advanced",
    text: "Arrive at destination with fresh gratitude",
    textAr: "الوصول إلى الوجهة بامتنان متجدد",
  },
];

export const EDUCATION_ENTRIES: EducationEntry[] = [
  {
    id: "edu_001",
    title: "The Foundation: Actions by Intentions",
    titleAr: "الأساس: الأعمال بالنيات",
    category: "Foundations",
    content: "The Prophet ﷺ said: 'Actions are only by intentions, and every person will have only what they intended.' This hadith is considered one of the most fundamental in Islam. It means that the spiritual worth of any deed is determined by the intention behind it. Even ordinary acts—eating, sleeping, working—become worship when done with the right niyyah.",
    contentAr: "قال النبي ﷺ: 'إنما الأعمال بالنيات، وإنما لكل امرئ ما نوى.' يُعدّ هذا الحديث من أهم أحاديث الإسلام. معناه أن القيمة الروحية لأي عمل تتحدد بالنية وراءه. حتى الأعمال العادية—الأكل والنوم والعمل—تصبح عبادة بالنية الصحيحة.",
    source: "Bukhari 1, Muslim 1907",
    keywords: ["intention", "niyyah", "foundation", "worship", "actions"],
  },
  {
    id: "edu_002",
    title: "Niyyah for Seeking Halal Provision",
    titleAr: "نية طلب الرزق الحلال",
    category: "Work",
    content: "The Prophet ﷺ said: 'Seeking halal provision is an obligation after the obligatory prayers.' When a Muslim works to provide for their family through lawful means, this is not merely a worldly act—it is an act of worship. Set your intention before starting work: 'I work to provide halal sustenance for my family and fulfill my responsibility before Allah.'",
    contentAr: "قال النبي ﷺ: 'طلب الحلال فريضة بعد الفريضة.' عندما يعمل المسلم لإعالة عائلته بوسائل مشروعة، فهذا ليس مجرد عمل دنيوي، بل هو عبادة. ضع نيتك قبل البدء في العمل.",
    source: "Tabarani, Al-Bayhaqi",
    keywords: ["work", "halal", "provision", "family", "earning"],
  },
  {
    id: "edu_003",
    title: "The Strong Believer and Exercise",
    titleAr: "المؤمن القوي والرياضة",
    category: "Health",
    content: "The Prophet ﷺ said: 'The strong believer is better and more beloved to Allah than the weak believer, though both are good.' Maintaining physical health is not vanity—it's a trust (amanah). When you exercise with the intention of maintaining Allah's trust, staying healthy for worship and service, every rep and every step becomes an act of devotion.",
    contentAr: "قال النبي ﷺ: 'المؤمن القوي خير وأحب إلى الله من المؤمن الضعيف، وفي كل خير.' الحفاظ على الصحة الجسدية ليس غروراً، بل هو أمانة.",
    source: "Muslim 2664",
    keywords: ["exercise", "health", "strong", "believer", "body"],
  },
  {
    id: "edu_004",
    title: "Sleeping with Remembrance",
    titleAr: "النوم بالذكر",
    category: "Daily Life",
    content: "The Prophet ﷺ instructed: 'When you go to bed, perform ablution as for prayer, then lie on your right side.' Sleep with Dhikr: recite Ayat al-Kursi, Al-Ikhlas, Al-Falaq, and An-Nas. Intend your sleep as rest to worship Allah better. The Prophet ﷺ said whoever falls asleep remembering Allah has it recorded as if they spent the night in worship.",
    contentAr: "أمر النبي ﷺ: 'إذا أتيت مضجعك فتوضأ وضوءك للصلاة، ثم اضطجع على شقك الأيمن.' نم بالذكر.",
    source: "Bukhari 247",
    keywords: ["sleep", "night", "dhikr", "remembrance", "rest"],
  },
  {
    id: "edu_005",
    title: "Niyyah for Eating",
    titleAr: "نية الأكل",
    category: "Daily Life",
    content: "The Prophet ﷺ said: 'Say Bismillah, eat with your right hand, and eat from what is closest to you.' Eating with intention transforms a biological necessity into worship. Before meals, intend: to nourish your body as Allah's trust, to gain energy for worship, and to be grateful for Allah's provision. Saying Bismillah is the verbal expression of this intention.",
    contentAr: "قال النبي ﷺ: 'قل بسم الله، وكل بيمينك، وكل مما يليك.' الأكل بنية يحول ضرورة بيولوجية إلى عبادة.",
    source: "Bukhari 5376, Muslim 2022",
    keywords: ["eating", "food", "bismillah", "meal", "gratitude"],
  },
  {
    id: "edu_006",
    title: "The Middle Prayer: Asr",
    titleAr: "الصلاة الوسطى: العصر",
    category: "Worship",
    content: "Allah says in the Quran: 'Guard strictly the prayers, especially the middle prayer (Asr), and stand before Allah in devotion.' (2:238). The Prophet ﷺ warned: 'Whoever misses Asr prayer, it is as though he has lost his family and wealth.' Renew your intention for Asr: to obey Allah's specific command for this prayer.",
    contentAr: "قال الله تعالى: 'حَافِظُوا عَلَى الصَّلَوَاتِ وَالصَّلَاةِ الْوُسْطَىٰ.' (2:238).",
    source: "Quran 2:238, Bukhari 552",
    keywords: ["asr", "prayer", "middle", "obligation", "worship"],
  },
  {
    id: "edu_007",
    title: "Seeking Knowledge as Worship",
    titleAr: "طلب العلم عبادة",
    category: "Learning",
    content: "The Prophet ﷺ said: 'Seeking knowledge is an obligation upon every Muslim.' Whether you're studying for work, reading, or learning a skill—if your intention is to better fulfill your duties to Allah and His creation, it becomes worship. Scholars say: 'An hour of learning can be worth more than a night of optional prayers.'",
    contentAr: "قال النبي ﷺ: 'طلب العلم فريضة على كل مسلم.' سواء كنت تدرس للعمل أو تقرأ أو تتعلم مهارة.",
    source: "Ibn Majah 224",
    keywords: ["knowledge", "learning", "study", "education", "obligation"],
  },
  {
    id: "edu_008",
    title: "Charity: Multiplied Beyond Measure",
    titleAr: "الصدقة: تُضاعف بلا حدود",
    category: "Worship",
    content: "Allah says: 'The example of those who spend their wealth in the way of Allah is like a seed of grain which grows seven spikes; in each spike is a hundred grains.' (2:261). The Prophet ﷺ said: 'Charity does not decrease wealth.' When giving, intend it purely for Allah, without expecting praise—and trust in Allah's promise of multiplication.",
    contentAr: "قال الله تعالى: 'مَّثَلُ الَّذِينَ يُنفِقُونَ أَمْوَالَهُمْ فِي سَبِيلِ اللَّهِ كَمَثَلِ حَبَّةٍ أَنبَتَتْ سَبْعَ سَنَابِلَ.' (2:261).",
    source: "Quran 2:261, Muslim 2588",
    keywords: ["charity", "sadaqah", "giving", "wealth", "reward"],
  },
  {
    id: "edu_009",
    title: "Family: A Sacred Responsibility",
    titleAr: "الأسرة: مسؤولية مقدسة",
    category: "Relationships",
    content: "The Prophet ﷺ said: 'The best of you are those who are best to their families.' Every moment with family—dinner conversations, helping children, comforting a spouse—can be worship when done with intention. The Prophet ﷺ even said that a morsel of food you put in your wife's mouth is charity. Family time with the right intention multiplies your ajr.",
    contentAr: "قال النبي ﷺ: 'خيركم خيركم لأهله.' كل لحظة مع الأسرة يمكن أن تكون عبادة بالنية الصحيحة.",
    source: "Tirmidhi 3895",
    keywords: ["family", "spouse", "children", "relationships", "care"],
  },
  {
    id: "edu_010",
    title: "The Power of Renewing Intentions",
    titleAr: "قوة تجديد النيات",
    category: "Foundations",
    content: "Scholars of the heart explain that intentions can weaken throughout an action. You may begin eating with Bismillah but drift into mindless eating. This is why renewing your intention (tajdid al-niyyah) mid-activity is powerful. A constant renewal keeps your heart connected to Allah throughout the day, turning every moment into a continuous act of worship.",
    contentAr: "يشرح علماء القلب أن النيات قد تضعف أثناء العمل. قد تبدأ بالأكل بسم الله لكن تنجرف إلى الأكل بلا وعي. لهذا فإن تجديد النية أثناء النشاط قوي.",
    source: "Ibn al-Qayyim, Madarij al-Salikin",
    keywords: ["renewal", "tajdid", "heart", "consciousness", "mindfulness"],
  },
  {
    id: "edu_011",
    title: "Multiplying Intentions, Multiplying Ajr",
    titleAr: "تضخيم النيات، تضخيم الأجر",
    category: "Foundations",
    content: "Ibn al-Qayyim wrote that a single act can carry many intentions simultaneously, and each intention earns its own reward. When you eat with five intentions—strength for worship, Sunnah manners, gratitude, family provision, and avoiding wastefulness—you receive the ajr of five acts of worship from one meal. This layering of intentions is the secret of the productive believer.",
    contentAr: "كتب ابن القيم أن العمل الواحد يمكن أن يحمل نيات كثيرة في آن واحد، وكل نية تكسب أجرها الخاص. عندما تأكل بخمس نيات، تحصل على أجر خمس عبادات من وجبة واحدة.",
    source: "Ibn al-Qayyim, Madarij al-Salikin vol. 3",
    keywords: ["multiply", "ajr", "reward", "layered", "intentions", "ibadah"],
  },
  {
    id: "edu_012",
    title: "Fajr: The Most Witnessed Prayer",
    titleAr: "الفجر: أكثر الصلوات شهوداً",
    category: "Worship",
    content: "Allah says: 'Establish prayer at the decline of the sun until the darkness of the night and the Quran of dawn. Indeed, the recitation of dawn is ever witnessed.' (17:78). The Prophet ﷺ said: 'The two rak'ahs of Fajr are better than this world and all it contains.' Starting your day with Fajr, with full intention and presence, sets a sacred tone for everything that follows.",
    contentAr: "قال الله تعالى: 'إِنَّ قُرْآنَ الْفَجْرِ كَانَ مَشْهُودًا.' (17:78).",
    source: "Quran 17:78, Muslim 725",
    keywords: ["fajr", "dawn", "prayer", "morning", "witnessed"],
  },
  {
    id: "edu_013",
    title: "Cleanliness: Half of Faith",
    titleAr: "النظافة: نصف الإيمان",
    category: "Daily Life",
    content: "The Prophet ﷺ said: 'Cleanliness is half of faith.' (Muslim 223). When you clean your home, maintain wudu, or wash before prayer, intend it as an act of faith. The homemaker who cleans with intention is not just doing housework—they are performing an act of ibadah that keeps them in a constant state of worship throughout the day.",
    contentAr: "قال النبي ﷺ: 'الطهور شطر الإيمان.' (مسلم 223). عندما تنظف بيتك أو تحافظ على وضوئك، انوِ ذلك كعمل إيماني.",
    source: "Muslim 223",
    keywords: ["cleanliness", "tahara", "purity", "home", "faith", "wudu"],
  },
  {
    id: "edu_014",
    title: "Making Du'a Before Activities",
    titleAr: "الدعاء قبل الأنشطة",
    category: "Worship",
    content: "The Prophet ﷺ had a du'a for almost every activity: entering the home, leaving the home, entering the bathroom, eating, sleeping, waking up. These prophetic du'as are themselves forms of niyyah—verbal declarations of awareness of Allah in each moment. Learning and using these du'as transforms your entire day into a continuous remembrance.",
    contentAr: "كان للنبي ﷺ دعاء لكل نشاط تقريباً. هذه الأدعية النبوية هي في حد ذاتها أشكال من النية.",
    source: "Bukhari, Muslim - Various",
    keywords: ["dua", "supplication", "prophetic", "remembrance", "daily"],
  },
  {
    id: "edu_015",
    title: "The Believer's Day as Worship",
    titleAr: "يوم المؤمن عبادة",
    category: "Foundations",
    content: "The companions of the Prophet ﷺ lived with continuous consciousness of Allah (muraqabah). They understood that Islam is not a weekend religion or a ritual-only practice—it is a complete way of life. When you wake with niyyah, eat with niyyah, work with niyyah, and sleep with niyyah, your entire day becomes an unbroken thread of worship connecting you to Allah.",
    contentAr: "عاش صحابة النبي ﷺ مع وعي مستمر بالله (المراقبة). أدركوا أن الإسلام ليس دين عطلة نهاية الأسبوع.",
    source: "General Islamic scholarship",
    keywords: ["consciousness", "muraqabah", "daily life", "worship", "lifestyle"],
  },
];

export const CATEGORY_COLORS: Record<string, string> = {
  worship: "#C9A84C",
  daily: "#2D7A4F",
  productivity: "#3B82F6",
  health: "#EF4444",
  relationships: "#EC4899",
  learning: "#8B5CF6",
};

export const HADITH_OPENER = {
  en: '"Actions are only by intentions, and every person will have only what they intended."',
  ar: '"إنما الأعمال بالنيات، وإنما لكل امرئ ما نوى."',
  ref: "— Prophet Muhammad ﷺ (Bukhari & Muslim)",
};

/** Returns niyyah options for a given activityId */
export function getNiyyahOptions(
  activityId: string,
  profileTags: string[] = []
): NiyyahOption[] {
  return NIYYAH_OPTIONS.filter(
    (n) =>
      n.activityId === activityId &&
      (!n.profileTag || profileTags.includes(n.profileTag))
  );
}
